### ISSUE TITLE
tsdate best practices

### ISSUE THREAD

**Issue by barneyhill** [tskit-dev/tsdate#318]
I'm getting ready to run tsdate on my inferred tree sequence (just chr21 at the moment for UKB 450K exomes + array data filtered to MAF > 0.001 + phased w/ SHAPEIT5). I have run tsinfer with the additional parameter:

```
truncate:
  - lower: 0.4
    upper: 0.6
    multiplier: 1
```

Are there any gotcha's I should be aware of before running tsdate? At the moment I am just planning to run:

```
inferred_ts = inferred_ts.simplify()
dated_ts = tsdate.date(inferred_ts, Ne=10000, mutation_rate=1e-8)
```

Many Thanks,
Barney
